### ISSUE TITLE
How to change sourceDestDir for cxf-boot-simple.

### ISSUE THREAD

**Issue by 333f1t51b21c1p69mf86ctw611258** [codecentric/spring-samples#2]
I don't want to generate sources and place in target folder
so how to change pom.xml configuration?

**Comment by jonashackt** [comment]
The project cxf-boot-simple uses the [cxf-spring-boot-starter](https://github.com/codecentric/cxf-spring-boot-starter), which makes heavy use of WSDL/XSD-to-Code generation (with JAXB) and is a kind of demo project for this starter. So to make it stop generating, doesn´t seem like the right direction :)

**Comment by 333f1t51b21c1p69mf86ctw611258** [comment]
Nope, I mean that could we change the generated path,
I want to move them to src/ folder.

**Comment by jonashackt** [comment]
They are no Source, that one want´s to check into version control - because, if the WSDL changes, the code would be broken. So it´s best practice and an architectural goal of the https://github.com/codecentric/cxf-spring-boot-starter-maven-plugin to generate only into target, which is the Maven default path for generated stuff. Therefore we wont change something here, I´am afraid.
